on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push Day7 

jobs:
  web-deploy:
    name: 🎉 Deploy website Day7 
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      # sync files via FTP
      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.dot-zerone.com
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: /day7/